# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kwartet.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NextTurnButton(object):
    def setupUi(self, NextTurnButton):
        NextTurnButton.setObjectName(_fromUtf8("NextTurnButton"))
        NextTurnButton.resize(1117, 879)
        self.gridLayout = QtGui.QGridLayout(NextTurnButton)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.StartButton = QtGui.QPushButton(NextTurnButton)
        self.StartButton.setObjectName(_fromUtf8("StartButton"))
        self.gridLayout.addWidget(self.StartButton, 0, 0, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(NextTurnButton)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.Player2Label = QtGui.QLabel(NextTurnButton)
        self.Player2Label.setObjectName(_fromUtf8("Player2Label"))
        self.gridLayout.addWidget(self.Player2Label, 0, 4, 1, 1)
        self.Player2ViewCheckbox = QtGui.QCheckBox(NextTurnButton)
        self.Player2ViewCheckbox.setObjectName(_fromUtf8("Player2ViewCheckbox"))
        self.gridLayout.addWidget(self.Player2ViewCheckbox, 0, 5, 1, 1)
        self.ResetButton = QtGui.QPushButton(NextTurnButton)
        self.ResetButton.setObjectName(_fromUtf8("ResetButton"))
        self.gridLayout.addWidget(self.ResetButton, 1, 0, 1, 1)
        self.FinishButton = QtGui.QPushButton(NextTurnButton)
        self.FinishButton.setObjectName(_fromUtf8("FinishButton"))
        self.gridLayout.addWidget(self.FinishButton, 1, 1, 1, 1)
        self.Player2Card = QtGui.QLabel(NextTurnButton)
        self.Player2Card.setText(_fromUtf8(""))
        self.Player2Card.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/SQ.png")))
        self.Player2Card.setScaledContents(False)
        self.Player2Card.setObjectName(_fromUtf8("Player2Card"))
        self.gridLayout.addWidget(self.Player2Card, 2, 2, 1, 1)
        self.Player2Card_2 = QtGui.QLabel(NextTurnButton)
        self.Player2Card_2.setText(_fromUtf8(""))
        self.Player2Card_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/DK.png")))
        self.Player2Card_2.setObjectName(_fromUtf8("Player2Card_2"))
        self.gridLayout.addWidget(self.Player2Card_2, 2, 3, 1, 1)
        self.Player2Card_4 = QtGui.QLabel(NextTurnButton)
        self.Player2Card_4.setText(_fromUtf8(""))
        self.Player2Card_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C5.png")))
        self.Player2Card_4.setObjectName(_fromUtf8("Player2Card_4"))
        self.gridLayout.addWidget(self.Player2Card_4, 2, 4, 1, 1)
        self.Player2Card_6 = QtGui.QLabel(NextTurnButton)
        self.Player2Card_6.setText(_fromUtf8(""))
        self.Player2Card_6.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C3.png")))
        self.Player2Card_6.setObjectName(_fromUtf8("Player2Card_6"))
        self.gridLayout.addWidget(self.Player2Card_6, 2, 5, 1, 1)
        self.Player2Card_8 = QtGui.QLabel(NextTurnButton)
        self.Player2Card_8.setText(_fromUtf8(""))
        self.Player2Card_8.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C10.png")))
        self.Player2Card_8.setObjectName(_fromUtf8("Player2Card_8"))
        self.gridLayout.addWidget(self.Player2Card_8, 2, 6, 1, 1)
        self.Player2Card_10 = QtGui.QLabel(NextTurnButton)
        self.Player2Card_10.setText(_fromUtf8(""))
        self.Player2Card_10.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C2.png")))
        self.Player2Card_10.setObjectName(_fromUtf8("Player2Card_10"))
        self.gridLayout.addWidget(self.Player2Card_10, 2, 7, 1, 1)
        self.Player2Card_12 = QtGui.QLabel(NextTurnButton)
        self.Player2Card_12.setText(_fromUtf8(""))
        self.Player2Card_12.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/H7.png")))
        self.Player2Card_12.setObjectName(_fromUtf8("Player2Card_12"))
        self.gridLayout.addWidget(self.Player2Card_12, 2, 8, 1, 1)
        self.Player2Card_3 = QtGui.QLabel(NextTurnButton)
        self.Player2Card_3.setText(_fromUtf8(""))
        self.Player2Card_3.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/KK.png")))
        self.Player2Card_3.setObjectName(_fromUtf8("Player2Card_3"))
        self.gridLayout.addWidget(self.Player2Card_3, 3, 3, 1, 1)
        self.Player2Card_5 = QtGui.QLabel(NextTurnButton)
        self.Player2Card_5.setText(_fromUtf8(""))
        self.Player2Card_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C8.png")))
        self.Player2Card_5.setObjectName(_fromUtf8("Player2Card_5"))
        self.gridLayout.addWidget(self.Player2Card_5, 3, 4, 1, 1)
        self.Player2Card_7 = QtGui.QLabel(NextTurnButton)
        self.Player2Card_7.setText(_fromUtf8(""))
        self.Player2Card_7.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C7.png")))
        self.Player2Card_7.setObjectName(_fromUtf8("Player2Card_7"))
        self.gridLayout.addWidget(self.Player2Card_7, 3, 5, 1, 1)
        self.Player2Card_9 = QtGui.QLabel(NextTurnButton)
        self.Player2Card_9.setText(_fromUtf8(""))
        self.Player2Card_9.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C5.png")))
        self.Player2Card_9.setObjectName(_fromUtf8("Player2Card_9"))
        self.gridLayout.addWidget(self.Player2Card_9, 3, 6, 1, 1)
        self.Player2Card_11 = QtGui.QLabel(NextTurnButton)
        self.Player2Card_11.setText(_fromUtf8(""))
        self.Player2Card_11.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C5.png")))
        self.Player2Card_11.setObjectName(_fromUtf8("Player2Card_11"))
        self.gridLayout.addWidget(self.Player2Card_11, 3, 7, 1, 1)
        self.Player2Card_13 = QtGui.QLabel(NextTurnButton)
        self.Player2Card_13.setText(_fromUtf8(""))
        self.Player2Card_13.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C1.png")))
        self.Player2Card_13.setObjectName(_fromUtf8("Player2Card_13"))
        self.gridLayout.addWidget(self.Player2Card_13, 3, 8, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 7, 1, 1)
        self.Player3Card = QtGui.QLabel(NextTurnButton)
        self.Player3Card.setText(_fromUtf8(""))
        self.Player3Card.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C1.png")))
        self.Player3Card.setScaledContents(False)
        self.Player3Card.setObjectName(_fromUtf8("Player3Card"))
        self.gridLayout.addWidget(self.Player3Card, 6, 1, 1, 1)
        self.Player3Card_2 = QtGui.QLabel(NextTurnButton)
        self.Player3Card_2.setText(_fromUtf8(""))
        self.Player3Card_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/D9.png")))
        self.Player3Card_2.setObjectName(_fromUtf8("Player3Card_2"))
        self.gridLayout.addWidget(self.Player3Card_2, 6, 2, 1, 1)
        self.Player3Card_3 = QtGui.QLabel(NextTurnButton)
        self.Player3Card_3.setText(_fromUtf8(""))
        self.Player3Card_3.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C2.png")))
        self.Player3Card_3.setObjectName(_fromUtf8("Player3Card_3"))
        self.gridLayout.addWidget(self.Player3Card_3, 6, 3, 1, 1)
        self.Player1Card = QtGui.QLabel(NextTurnButton)
        self.Player1Card.setText(_fromUtf8(""))
        self.Player1Card.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/S6.png")))
        self.Player1Card.setObjectName(_fromUtf8("Player1Card"))
        self.gridLayout.addWidget(self.Player1Card, 6, 7, 1, 1)
        self.Player1Card_3 = QtGui.QLabel(NextTurnButton)
        self.Player1Card_3.setText(_fromUtf8(""))
        self.Player1Card_3.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C6.png")))
        self.Player1Card_3.setObjectName(_fromUtf8("Player1Card_3"))
        self.gridLayout.addWidget(self.Player1Card_3, 6, 8, 1, 1)
        self.Player1Card_2 = QtGui.QLabel(NextTurnButton)
        self.Player1Card_2.setText(_fromUtf8(""))
        self.Player1Card_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C8.png")))
        self.Player1Card_2.setObjectName(_fromUtf8("Player1Card_2"))
        self.gridLayout.addWidget(self.Player1Card_2, 6, 9, 1, 1)
        self.Player3Label = QtGui.QLabel(NextTurnButton)
        self.Player3Label.setObjectName(_fromUtf8("Player3Label"))
        self.gridLayout.addWidget(self.Player3Label, 7, 0, 1, 1)
        self.Player3Card_6 = QtGui.QLabel(NextTurnButton)
        self.Player3Card_6.setText(_fromUtf8(""))
        self.Player3Card_6.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C10.png")))
        self.Player3Card_6.setObjectName(_fromUtf8("Player3Card_6"))
        self.gridLayout.addWidget(self.Player3Card_6, 7, 1, 1, 1)
        self.Player3Card_5 = QtGui.QLabel(NextTurnButton)
        self.Player3Card_5.setText(_fromUtf8(""))
        self.Player3Card_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/D7.png")))
        self.Player3Card_5.setObjectName(_fromUtf8("Player3Card_5"))
        self.gridLayout.addWidget(self.Player3Card_5, 7, 2, 1, 1)
        self.Player3Card_4 = QtGui.QLabel(NextTurnButton)
        self.Player3Card_4.setText(_fromUtf8(""))
        self.Player3Card_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/DK.png")))
        self.Player3Card_4.setObjectName(_fromUtf8("Player3Card_4"))
        self.gridLayout.addWidget(self.Player3Card_4, 7, 3, 1, 1)
        self.Player1Card_4 = QtGui.QLabel(NextTurnButton)
        self.Player1Card_4.setText(_fromUtf8(""))
        self.Player1Card_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/H5.png")))
        self.Player1Card_4.setObjectName(_fromUtf8("Player1Card_4"))
        self.gridLayout.addWidget(self.Player1Card_4, 7, 7, 1, 1)
        self.Player1Card_5 = QtGui.QLabel(NextTurnButton)
        self.Player1Card_5.setText(_fromUtf8(""))
        self.Player1Card_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C8.png")))
        self.Player1Card_5.setObjectName(_fromUtf8("Player1Card_5"))
        self.gridLayout.addWidget(self.Player1Card_5, 7, 8, 1, 1)
        self.Player1Card_6 = QtGui.QLabel(NextTurnButton)
        self.Player1Card_6.setText(_fromUtf8(""))
        self.Player1Card_6.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/SJ.png")))
        self.Player1Card_6.setObjectName(_fromUtf8("Player1Card_6"))
        self.gridLayout.addWidget(self.Player1Card_6, 7, 9, 1, 1)
        self.Player1Label = QtGui.QLabel(NextTurnButton)
        self.Player1Label.setMaximumSize(QtCore.QSize(16777215, 71))
        self.Player1Label.setObjectName(_fromUtf8("Player1Label"))
        self.gridLayout.addWidget(self.Player1Label, 7, 10, 1, 1)
        self.Player3ViewCheckbox = QtGui.QCheckBox(NextTurnButton)
        self.Player3ViewCheckbox.setObjectName(_fromUtf8("Player3ViewCheckbox"))
        self.gridLayout.addWidget(self.Player3ViewCheckbox, 8, 0, 1, 1)
        self.Player3Card_9 = QtGui.QLabel(NextTurnButton)
        self.Player3Card_9.setText(_fromUtf8(""))
        self.Player3Card_9.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C2.png")))
        self.Player3Card_9.setObjectName(_fromUtf8("Player3Card_9"))
        self.gridLayout.addWidget(self.Player3Card_9, 8, 1, 1, 1)
        self.Player3Card_8 = QtGui.QLabel(NextTurnButton)
        self.Player3Card_8.setText(_fromUtf8(""))
        self.Player3Card_8.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/SJ.png")))
        self.Player3Card_8.setObjectName(_fromUtf8("Player3Card_8"))
        self.gridLayout.addWidget(self.Player3Card_8, 8, 2, 1, 1)
        self.Player3Card_7 = QtGui.QLabel(NextTurnButton)
        self.Player3Card_7.setText(_fromUtf8(""))
        self.Player3Card_7.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/H5.png")))
        self.Player3Card_7.setObjectName(_fromUtf8("Player3Card_7"))
        self.gridLayout.addWidget(self.Player3Card_7, 8, 3, 1, 1)
        self.Player1Card_7 = QtGui.QLabel(NextTurnButton)
        self.Player1Card_7.setText(_fromUtf8(""))
        self.Player1Card_7.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/H5.png")))
        self.Player1Card_7.setObjectName(_fromUtf8("Player1Card_7"))
        self.gridLayout.addWidget(self.Player1Card_7, 8, 7, 1, 1)
        self.Player1Card_8 = QtGui.QLabel(NextTurnButton)
        self.Player1Card_8.setText(_fromUtf8(""))
        self.Player1Card_8.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C6.png")))
        self.Player1Card_8.setObjectName(_fromUtf8("Player1Card_8"))
        self.gridLayout.addWidget(self.Player1Card_8, 8, 8, 1, 1)
        self.Player1Card_9 = QtGui.QLabel(NextTurnButton)
        self.Player1Card_9.setText(_fromUtf8(""))
        self.Player1Card_9.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/HQ.png")))
        self.Player1Card_9.setObjectName(_fromUtf8("Player1Card_9"))
        self.gridLayout.addWidget(self.Player1Card_9, 8, 9, 1, 1)
        self.Player1ViewCheckbox = QtGui.QCheckBox(NextTurnButton)
        self.Player1ViewCheckbox.setObjectName(_fromUtf8("Player1ViewCheckbox"))
        self.gridLayout.addWidget(self.Player1ViewCheckbox, 8, 10, 1, 1)
        self.Player3Card_12 = QtGui.QLabel(NextTurnButton)
        self.Player3Card_12.setText(_fromUtf8(""))
        self.Player3Card_12.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/S6.png")))
        self.Player3Card_12.setObjectName(_fromUtf8("Player3Card_12"))
        self.gridLayout.addWidget(self.Player3Card_12, 9, 1, 1, 1)
        self.Player3Card_11 = QtGui.QLabel(NextTurnButton)
        self.Player3Card_11.setText(_fromUtf8(""))
        self.Player3Card_11.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/SJ.png")))
        self.Player3Card_11.setObjectName(_fromUtf8("Player3Card_11"))
        self.gridLayout.addWidget(self.Player3Card_11, 9, 2, 1, 1)
        self.Player3Card_10 = QtGui.QLabel(NextTurnButton)
        self.Player3Card_10.setText(_fromUtf8(""))
        self.Player3Card_10.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C5.png")))
        self.Player3Card_10.setObjectName(_fromUtf8("Player3Card_10"))
        self.gridLayout.addWidget(self.Player3Card_10, 9, 3, 1, 1)
        self.Player1Card_10 = QtGui.QLabel(NextTurnButton)
        self.Player1Card_10.setText(_fromUtf8(""))
        self.Player1Card_10.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/DQ.png")))
        self.Player1Card_10.setObjectName(_fromUtf8("Player1Card_10"))
        self.gridLayout.addWidget(self.Player1Card_10, 9, 7, 1, 1)
        self.Player1Card8 = QtGui.QLabel(NextTurnButton)
        self.Player1Card8.setText(_fromUtf8(""))
        self.Player1Card8.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C8.png")))
        self.Player1Card8.setObjectName(_fromUtf8("Player1Card8"))
        self.gridLayout.addWidget(self.Player1Card8, 9, 8, 1, 1)
        self.Player1Card_11 = QtGui.QLabel(NextTurnButton)
        self.Player1Card_11.setText(_fromUtf8(""))
        self.Player1Card_11.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/D9.png")))
        self.Player1Card_11.setObjectName(_fromUtf8("Player1Card_11"))
        self.gridLayout.addWidget(self.Player1Card_11, 9, 9, 1, 1)
        self.Player3Card_13 = QtGui.QLabel(NextTurnButton)
        self.Player3Card_13.setText(_fromUtf8(""))
        self.Player3Card_13.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/H4.png")))
        self.Player3Card_13.setObjectName(_fromUtf8("Player3Card_13"))
        self.gridLayout.addWidget(self.Player3Card_13, 10, 1, 1, 1)
        self.Player1Card_12 = QtGui.QLabel(NextTurnButton)
        self.Player1Card_12.setText(_fromUtf8(""))
        self.Player1Card_12.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/D9.png")))
        self.Player1Card_12.setObjectName(_fromUtf8("Player1Card_12"))
        self.gridLayout.addWidget(self.Player1Card_12, 10, 7, 1, 1)
        self.Player1Card_13 = QtGui.QLabel(NextTurnButton)
        self.Player1Card_13.setText(_fromUtf8(""))
        self.Player1Card_13.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/S4.png")))
        self.Player1Card_13.setObjectName(_fromUtf8("Player1Card_13"))
        self.gridLayout.addWidget(self.Player1Card_13, 10, 8, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 11, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 11, 7, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 11, 8, 1, 1)
        self.Player4Card = QtGui.QLabel(NextTurnButton)
        self.Player4Card.setText(_fromUtf8(""))
        self.Player4Card.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/H5.png")))
        self.Player4Card.setObjectName(_fromUtf8("Player4Card"))
        self.gridLayout.addWidget(self.Player4Card, 12, 2, 1, 1)
        self.Player4Card_2 = QtGui.QLabel(NextTurnButton)
        self.Player4Card_2.setText(_fromUtf8(""))
        self.Player4Card_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C1.png")))
        self.Player4Card_2.setObjectName(_fromUtf8("Player4Card_2"))
        self.gridLayout.addWidget(self.Player4Card_2, 12, 3, 1, 1)
        self.Player4Card_3 = QtGui.QLabel(NextTurnButton)
        self.Player4Card_3.setText(_fromUtf8(""))
        self.Player4Card_3.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C1.png")))
        self.Player4Card_3.setObjectName(_fromUtf8("Player4Card_3"))
        self.gridLayout.addWidget(self.Player4Card_3, 12, 4, 1, 1)
        self.Player4Card_4 = QtGui.QLabel(NextTurnButton)
        self.Player4Card_4.setText(_fromUtf8(""))
        self.Player4Card_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/H3.png")))
        self.Player4Card_4.setObjectName(_fromUtf8("Player4Card_4"))
        self.gridLayout.addWidget(self.Player4Card_4, 12, 5, 1, 1)
        self.Player4Card_5 = QtGui.QLabel(NextTurnButton)
        self.Player4Card_5.setText(_fromUtf8(""))
        self.Player4Card_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C5.png")))
        self.Player4Card_5.setObjectName(_fromUtf8("Player4Card_5"))
        self.gridLayout.addWidget(self.Player4Card_5, 12, 6, 1, 1)
        self.Player4Card_6 = QtGui.QLabel(NextTurnButton)
        self.Player4Card_6.setText(_fromUtf8(""))
        self.Player4Card_6.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/H8.png")))
        self.Player4Card_6.setObjectName(_fromUtf8("Player4Card_6"))
        self.gridLayout.addWidget(self.Player4Card_6, 12, 7, 1, 1)
        self.Player4Card_7 = QtGui.QLabel(NextTurnButton)
        self.Player4Card_7.setText(_fromUtf8(""))
        self.Player4Card_7.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/H7.png")))
        self.Player4Card_7.setObjectName(_fromUtf8("Player4Card_7"))
        self.gridLayout.addWidget(self.Player4Card_7, 12, 8, 1, 1)
        self.Player4Card_8 = QtGui.QLabel(NextTurnButton)
        self.Player4Card_8.setText(_fromUtf8(""))
        self.Player4Card_8.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/H8.png")))
        self.Player4Card_8.setObjectName(_fromUtf8("Player4Card_8"))
        self.gridLayout.addWidget(self.Player4Card_8, 13, 2, 1, 1)
        self.Player4Card_9 = QtGui.QLabel(NextTurnButton)
        self.Player4Card_9.setText(_fromUtf8(""))
        self.Player4Card_9.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/SJ.png")))
        self.Player4Card_9.setObjectName(_fromUtf8("Player4Card_9"))
        self.gridLayout.addWidget(self.Player4Card_9, 13, 3, 1, 1)
        self.Player4Card_10 = QtGui.QLabel(NextTurnButton)
        self.Player4Card_10.setText(_fromUtf8(""))
        self.Player4Card_10.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/S3.png")))
        self.Player4Card_10.setObjectName(_fromUtf8("Player4Card_10"))
        self.gridLayout.addWidget(self.Player4Card_10, 13, 4, 1, 1)
        self.Player4Card_11 = QtGui.QLabel(NextTurnButton)
        self.Player4Card_11.setText(_fromUtf8(""))
        self.Player4Card_11.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/D3.png")))
        self.Player4Card_11.setObjectName(_fromUtf8("Player4Card_11"))
        self.gridLayout.addWidget(self.Player4Card_11, 13, 5, 1, 1)
        self.Player4Card_12 = QtGui.QLabel(NextTurnButton)
        self.Player4Card_12.setText(_fromUtf8(""))
        self.Player4Card_12.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/C1.png")))
        self.Player4Card_12.setObjectName(_fromUtf8("Player4Card_12"))
        self.gridLayout.addWidget(self.Player4Card_12, 13, 6, 1, 1)
        self.Player4Card_13 = QtGui.QLabel(NextTurnButton)
        self.Player4Card_13.setText(_fromUtf8(""))
        self.Player4Card_13.setPixmap(QtGui.QPixmap(_fromUtf8(":/Cards/CardPngs/H5.png")))
        self.Player4Card_13.setObjectName(_fromUtf8("Player4Card_13"))
        self.gridLayout.addWidget(self.Player4Card_13, 13, 7, 1, 1)
        self.Turncounter = QtGui.QLCDNumber(NextTurnButton)
        self.Turncounter.setStyleSheet(_fromUtf8(""))
        self.Turncounter.setObjectName(_fromUtf8("Turncounter"))
        self.gridLayout.addWidget(self.Turncounter, 14, 0, 1, 1)
        self.Player4Label = QtGui.QLabel(NextTurnButton)
        self.Player4Label.setObjectName(_fromUtf8("Player4Label"))
        self.gridLayout.addWidget(self.Player4Label, 14, 3, 1, 1)
        self.Player4ViewCheckbox = QtGui.QCheckBox(NextTurnButton)
        self.Player4ViewCheckbox.setObjectName(_fromUtf8("Player4ViewCheckbox"))
        self.gridLayout.addWidget(self.Player4ViewCheckbox, 14, 4, 1, 1)
        self.actionssn = QtGui.QAction(NextTurnButton)
        self.actionssn.setObjectName(_fromUtf8("actionssn"))

        self.retranslateUi(NextTurnButton)
        QtCore.QMetaObject.connectSlotsByName(NextTurnButton)

    def retranslateUi(self, NextTurnButton):
        NextTurnButton.setWindowTitle(_translate("NextTurnButton", "Form", None))
        self.StartButton.setText(_translate("NextTurnButton", "Start", None))
        self.pushButton_3.setText(_translate("NextTurnButton", "Next Turn", None))
        self.Player2Label.setText(_translate("NextTurnButton", "<html><head/><body><p><span style=\" font-size:14pt; color:#005500;\">Player 2</span></p></body></html>", None))
        self.Player2ViewCheckbox.setText(_translate("NextTurnButton", "Player View", None))
        self.ResetButton.setText(_translate("NextTurnButton", "Reset", None))
        self.FinishButton.setText(_translate("NextTurnButton", "Finish", None))
        self.Player3Label.setText(_translate("NextTurnButton", "<html><head/><body><p><span style=\" font-size:14pt; color:#0000ff;\">Player 3</span></p></body></html>", None))
        self.Player1Label.setText(_translate("NextTurnButton", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Player 1</span></p></body></html>", None))
        self.Player3ViewCheckbox.setText(_translate("NextTurnButton", "Player View", None))
        self.Player1ViewCheckbox.setText(_translate("NextTurnButton", "Player View", None))
        self.Player4Label.setText(_translate("NextTurnButton", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff5500;\">Player 4</span></p></body></html>", None))
        self.Player4ViewCheckbox.setText(_translate("NextTurnButton", "Player View", None))
        self.actionssn.setText(_translate("NextTurnButton", "ssn", None))
        self.actionssn.setToolTip(_translate("NextTurnButton", "bg", None))

import rsrc_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    NextTurnButton = QtGui.QWidget()
    ui = Ui_NextTurnButton()
    ui.setupUi(NextTurnButton)
    NextTurnButton.show()
    sys.exit(app.exec_())

