# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kwartetsimple.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from datetime import datetime

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QPlainTextEdit

text = open('output.txt').read()





def find_correct_player_information(turn, player):
    correct_line = -100

    needed_line = "turn " + str(turn)

    with open("output.txt") as fp:
        for i, line in enumerate(fp):
            line = line[:-1]
            if line == needed_line:
                correct_line = i

            if i == (correct_line + player):
                turn += 1
                print(line)
                return line





class Ui_NextTurnButton(object):
    turn = 1

    def setupUi(self, NextTurnButton):
        NextTurnButton.setObjectName("NextTurnButton")
        NextTurnButton.resize(1117, 879)
        self.gridLayout = QtWidgets.QGridLayout(NextTurnButton)
        self.gridLayout.setObjectName("gridLayout")
        self.Player3Label = QtWidgets.QLabel(NextTurnButton)
        self.Player3Label.setObjectName("Player3Label")
        self.gridLayout.addWidget(self.Player3Label, 4, 1, 1, 1)
        self.Player1Label = QtWidgets.QLabel(NextTurnButton)
        self.Player1Label.setMaximumSize(QtCore.QSize(16777215, 71))
        self.Player1Label.setObjectName("Player1Label")
        self.gridLayout.addWidget(self.Player1Label, 4, 8, 1, 1)
        self.Plyr3_cards = QtWidgets.QLabel(NextTurnButton)
        self.Plyr3_cards.setObjectName("Plyr3_cards")
        self.gridLayout.addWidget(self.Plyr3_cards, 4, 2, 1, 1)
        self.NextPointbttn = QtWidgets.QPushButton(NextTurnButton)
        self.NextPointbttn.setObjectName("NextPointbttn")
        self.gridLayout.addWidget(self.NextPointbttn, 4, 9, 1, 1)
        self.StartBttn = QtWidgets.QPushButton(NextTurnButton)
        self.StartBttn.setObjectName("StartBttn")
        self.gridLayout.addWidget(self.StartBttn, 4, 0, 1, 1)
        self.Plyr4_cards = QtWidgets.QLabel(NextTurnButton)
        self.Plyr4_cards.setObjectName("Plyr4_cards")
        self.gridLayout.addWidget(self.Plyr4_cards, 5, 6, 1, 1)
        self.Plyr2_cards = QtWidgets.QLabel(NextTurnButton)
        self.Plyr2_cards.setObjectName("Plyr2_cards")
        self.gridLayout.addWidget(self.Plyr2_cards, 1, 6, 1, 1)
        self.Plyr1_cards = QtWidgets.QLabel(NextTurnButton)
        self.Plyr1_cards.setObjectName("Plyr1_cards")
        self.gridLayout.addWidget(self.Plyr1_cards, 4, 7, 1, 1)
        self.Player4Label = QtWidgets.QLabel(NextTurnButton)
        self.Player4Label.setObjectName("Player4Label")
        self.gridLayout.addWidget(self.Player4Label, 6, 6, 1, 1)
        self.Player2Label = QtWidgets.QLabel(NextTurnButton)
        self.Player2Label.setObjectName("Player2Label")
        self.gridLayout.addWidget(self.Player2Label, 0, 6, 1, 1)
        self.actionssn = QtWidgets.QAction(NextTurnButton)
        self.actionssn.setObjectName("actionssn")

        self.retranslateUi(NextTurnButton)
        self.StartBttn.clicked.connect(self.reset_label1)
        self.StartBttn.clicked.connect(self.reset_label2)
        self.StartBttn.clicked.connect(self.reset_label3)
        self.StartBttn.clicked.connect(self.reset_label4)
        self.NextPointbttn.clicked.connect(self.playnext)
        QtCore.QMetaObject.connectSlotsByName(NextTurnButton)
    def playnext(self):
        self.update_label1()
        self.update_label2()
        self.update_label3()
        self.update_label4()
        self.increaseturn()
    def retranslateUi(self, NextTurnButton):
        _translate = QtCore.QCoreApplication.translate
        NextTurnButton.setWindowTitle(_translate("NextTurnButton", "Form"))
        self.Player3Label.setText(_translate("NextTurnButton",
                                             "<html><head/><body><p><span style=\" font-size:14pt; color:#0000ff;\">Player 3</span></p></body></html>"))
        self.Player1Label.setText(_translate("NextTurnButton",
                                             "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Player 1</span></p></body></html>"))
        self.Plyr3_cards.setText(_translate("NextTurnButton", "Player 3 Cards"))
        self.NextPointbttn.setText(_translate("NextTurnButton", "Next Turn"))
        self.StartBttn.setText(_translate("NextTurnButton", "Start"))
        self.Plyr4_cards.setText(_translate("NextTurnButton", "Player 4 Cards"))
        self.Plyr2_cards.setText(_translate("NextTurnButton", "Player 2 Cards"))
        self.Plyr1_cards.setText(_translate("NextTurnButton", "Player 1 Cards"))
        self.Player4Label.setText(_translate("NextTurnButton",
                                             "<html><head/><body><p><span style=\" font-size:14pt; color:#ff5500;\">Player 4</span></p></body></html>"))
        self.Player2Label.setText(_translate("NextTurnButton",
                                             "<html><head/><body><p><span style=\" font-size:14pt; color:#005500;\">Player 2</span></p></body></html>"))
        self.actionssn.setText(_translate("NextTurnButton", "ssn"))
        self.actionssn.setToolTip(_translate("NextTurnButton", "bg"))

    def update_label1(self):
        text = find_correct_player_information(self.turn, 1)
        self.Plyr1_cards.setText(text)



    def update_label2(self):
        text = find_correct_player_information(self.turn, 2)
        self.Plyr2_cards.setText(text)


    def update_label3(self):
        text = find_correct_player_information(self.turn, 3)
        self.Plyr3_cards.setText(text)
        print(self.turn, 'abcc')


    def update_label4(self):

        text = find_correct_player_information(self.turn, 4)
        self.Plyr4_cards.setText(text)
    def increaseturn(self):
        self.turn +=1

    def reset_label1(self):
        self.Plyr1_cards.setText(find_correct_player_information(1, 1))

    def reset_label2(self):
        self.Plyr2_cards.setText(find_correct_player_information(1, 2))

    def reset_label3(self):
        self.Plyr3_cards.setText(find_correct_player_information(1, 3))

    def reset_label4(self):
        self.Plyr4_cards.setText(find_correct_player_information(1, 4))


if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    NextTurnButton = QWidget()
    ui = Ui_NextTurnButton()
    ui.setupUi(NextTurnButton)
    NextTurnButton.show()





    ui.update_label1()
    ui.update_label2()
    ui.update_label3()
    ui.update_label4()






    sys.exit(app.exec_())
